@isTest
private class opptySunsetTaskControllerTest {

// COMMENTED OUT 20171215 AAB - WHAT THE HELL IS THIS CRAP?

  //  static testMethod void myUnitTest() {
    	
  //  	Opportunity o = new Opportunity();
  //  	o.Name = 'Test Opp';
  //  	o.StageName = 'G. Prospect';
  //  	o.CloseDate = System.Today();
  //  	o.Sunset_Notification_Created__c = true;
  //  	o.Client_Sponsor__c = 'Test Value';
  //  	insert o;
    	
  //  	test.startTest();
    	
		//opptySunsetTaskController clsTask = new opptySunsetTaskController(new ApexPages.StandardController(o));
		
		//clsTask.getRenderOpenProject();
		//clsTask.getRenderClosedProject();
		
		//o.Sunset_Notification_Created__c = false;
		//update o;
		
		//clsTask.getRenderOpenProject();
		//clsTask.getRenderClosedProject();
		
		//test.stopTest();

  //  }
}