public class opptySunsetTaskController {

// COMMENTED OUT 20171215 AAB - WHAT THE HELL IS THIS CRAP?

////manage which page blocks are displayed depending on if a sunset task has been created (project has been closed)

//	private final Opportunity oppty;
	
//	public opptySunsetTaskController(ApexPages.StandardController stdController) {
//    	this.oppty = (Opportunity)stdController.getRecord();
//	}
	
//	public boolean getRenderOpenProject() {
		
//		Boolean isClosed = oppty.Sunset_Notification_Created__c;
		
//		if(isClosed == true){
//			return false;}
//		else {
//			return true;}
//	}
	
//	public boolean getRenderClosedProject() {
		
//		Boolean isClosed = oppty.Sunset_Notification_Created__c;
		
//		if(isClosed == true){
//			return true;}
//		else {
//			return false;}
//		}
	
}