@isTest
private class resourceUpdate {
static testMethod void resourceUpdateUnitTest() {
 
        //Date dt = system.today();
        
        ////insert test resource
        //Resource__c testResource = new Resource__c(
            //name = 'Kevin Testperson',
            //Email_Address__c = 'kevin@gmail.com');
        
        //insert testResource;
    
        ////insert test account
        //Account testAccount = new Account(name = 'KDJ Test Account');
        
        //insert testAccount; 
        
        ////insert test oppty
        //Opportunity testOppty = new Opportunity( 
        	//StageName = 'Closed Won'
            //,Name = 'Test Opportunity'
            //,CloseDate = dt
            //,Amount = 1
            //,Hourly_Rate__c = 1
            //,Client_Sponsor__c = 'TEST'
            //,AccountId = testAccount.id
            //,Resource_One__c = testResource.id
        	//,Reason_for_Win_Loss_Abandoned__c='Won'
        //);
        //insert testOppty;
                
        //opp.StageName = 'Closed Lost';
        //update opp;
        
        //opp.StageName = 'Test';
        //update opp;
    }
}